[package]
name = "sty-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sty"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sty-core.workspace = true
sty-runner.workspace = true
tokio.workspace = true
