<script lang="ts">
  import Copy from 'lucide-svelte/icons/copy'; import Check from 'lucide-svelte/icons/check';
  import FormShell from '$lib/components/FormShell.svelte'; import { api, StyApiError } from '$lib/api';
  let token=$state('');let expiresAt=$state('');let busy=$state(false);let error=$state('');let copied=$state(false);
  const command=$derived(token?`sty runner register --url https://sty.sh --token ${token}`:'');
  async function create(){busy=true;error='';try{const result=await api<{enrollment:{token:string;expiresAt:string}}>('/runner-enrollments',{method:'POST',body:JSON.stringify({organization:'lantharos',expiresMinutes:15})});token=result.enrollment.token;expiresAt=result.enrollment.expiresAt}catch(cause){error=cause instanceof StyApiError?cause.message:'Enrollment could not be created.'}finally{busy=false}}
  async function copy(){await navigator.clipboard.writeText(command);copied=true;setTimeout(()=>copied=false,1400)}
</script>
<svelte:head><title>Connect runner · Sty</title></svelte:head>
<FormShell title="Connect a runner" description="Give one machine permission to pick up jobs for lantharos.">
  {#if token}<div class="ready"><strong>Run this on the machine</strong><p>The enrollment token works once and expires at {expiresAt}.</p><div><code>{command}</code><button aria-label="Copy runner command" onclick={copy}>{#if copied}<Check size={14}/>{:else}<Copy size={14}/>{/if}</button></div><a href="/runners">I’ll finish on the machine</a></div>{:else}<div class="explain"><p>The runner executes repository code with the authority of its service account. Use a dedicated machine or user when jobs should not reach your personal files.</p><dl><div><dt>Organization</dt><dd>lantharos</dd></div><div><dt>Enrollment window</dt><dd>15 minutes</dd></div><div><dt>Execution</dt><dd>Host machine</dd></div></dl>{#if error}<p class="error" role="alert">{error}</p>{/if}<button class="connect" disabled={busy} onclick={create}>{busy?'Creating…':'Create enrollment command'}</button></div>{/if}
</FormShell>
<style>
  .explain>p,.ready>p{margin:0 0 18px;color:var(--text-muted);font-size:10px;line-height:1.6}dl{margin:0;border-top:1px solid var(--border)}dl>div{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--border-subtle);font-size:10px}dt{color:var(--text-faint)}dd{margin:0;color:var(--text-strong)}.connect{display:flex;height:34px;align-items:center;margin:20px 0 0 auto;padding:0 11px;border:0;border-radius:6px;background:var(--brand);color:#fff;cursor:pointer;font-size:10px;font-weight:650}.connect:disabled{opacity:.5}.error{color:var(--danger)!important}.ready>strong{display:block;margin-bottom:5px;color:var(--text-strong);font-size:12px}.ready>div{display:grid;grid-template-columns:minmax(0,1fr) 36px;border:1px solid var(--border);border-radius:6px;background:var(--surface)}.ready code{overflow:auto;padding:12px;color:var(--text);font-size:9px;white-space:nowrap}.ready button{display:grid;border:0;border-left:1px solid var(--border);background:transparent;color:var(--text-muted);place-items:center;cursor:pointer}.ready>a{display:inline-block;margin-top:17px;color:var(--brand);font-size:10px;text-decoration:none}
</style>
