/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 088ee25e03b5cfa8e1781a6f76964083)
interface __BaseEnv_CloudflareBindings {
	REPOSITORIES: R2Bucket;
	MARL_API_URL: string;
	MARL_GIT_GATEWAY_TOKEN: string;
	GIT_CONTAINERS: DurableObjectNamespace<import("./src/index").GitContainer>;
	VALIDATOR_CONTAINERS: DurableObjectNamespace<import("./src/index").ValidatorContainer>;
	MAINTENANCE_CONTAINERS: DurableObjectNamespace<import("./src/index").MaintenanceContainer>;
	REPOSITORY_STATE: DurableObjectNamespace<import("./src/index").RepositoryStateObject>;
	ORGANIZATION_QUOTAS: DurableObjectNamespace<import("./src/index").OrganizationQuotaObject>;
	UPLOAD_SESSIONS: DurableObjectNamespace<import("./src/index").UploadSessionObject>;
	COMPACTIONS: DurableObjectNamespace<import("./src/index").CompactionObject>;
	INDEXING: DurableObjectNamespace<import("./src/index").RepositoryIndexObject>;
	MARL_API: Fetcher /* marl-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GitContainer" | "RepositoryStateObject" | "OrganizationQuotaObject" | "UploadSessionObject" | "ValidatorContainer" | "MaintenanceContainer" | "CompactionObject" | "RepositoryIndexObject";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MARL_API_URL" | "MARL_GIT_GATEWAY_TOKEN">> {}
}
