<script lang="ts">
  import BackLink from './BackLink.svelte';
  let { title, description, children }: { title: string; description: string; children: import('svelte').Snippet } = $props();
</script>

<main class="page"><header><BackLink href="/" label="Marl" /><h1>{title}</h1><p>{description}</p></header><section>{@render children()}</section></main>

<style>
  .page{width:min(680px,calc(100% - 40px));margin:0 auto;padding:52px 0 80px}.page>header{margin-bottom:29px}h1{margin:20px 0 0;color:var(--text-strong);font-size:26px;font-weight:650;letter-spacing:-.04em}p{margin:7px 0 0;color:var(--text-muted);font-size:12px}section{padding-top:22px;border-top:1px solid var(--border)}:global(.form-grid){display:grid;gap:18px}:global(.field-row){display:grid;grid-template-columns:1fr 1fr;gap:12px}:global(.field){display:grid;gap:7px}:global(.field>span){color:var(--text-strong);font-size:10px;font-weight:620}:global(.field small){color:var(--text-faint);font-size:9px;line-height:1.45}:global(.field input),:global(.field textarea){width:100%;border:1px solid var(--border-strong);border-radius:6px;outline:none;background:var(--surface);color:var(--text-strong);font-size:11px}:global(.field input){height:36px;padding:0 9px}:global(.field textarea){min-height:72px;resize:vertical;padding:9px}:global(.field input:focus),:global(.field textarea:focus){border-color:var(--brand);box-shadow:0 0 0 3px var(--brand-soft)}:global(.form-actions){display:flex;justify-content:flex-end;gap:7px;padding-top:18px;border-top:1px solid var(--border-subtle)}:global(.form-actions a),:global(.form-actions button){display:inline-flex;height:34px;align-items:center;padding:0 11px;border:1px solid var(--border);border-radius:6px;background:var(--surface);color:var(--text);cursor:pointer;font-size:10px;font-weight:630;text-decoration:none}:global(.form-actions button){border-color:var(--brand);background:var(--brand);color:#fff}:global(.form-actions button:hover){background:var(--brand-hover)}@media(max-width:600px){.page{width:calc(100% - 28px);padding-top:32px}:global(.field-row){grid-template-columns:1fr}}
</style>
