<script lang="ts">
  import BackLink from './BackLink.svelte';
  let { title, description, children }: { title: string; description: string; children: import('svelte').Snippet } = $props();
</script>

<main class="page"><header><BackLink href="/" label="Marl" /><h1>{title}</h1><p>{description}</p></header><section>{@render children()}</section></main>

<style>
  .page{width:min(680px,calc(100% - 48px));margin:0 auto;padding:44px 0 80px}.page>header{margin-bottom:28px}h1{margin:20px 0 0;color:var(--text-strong);font-size:28px;font-weight:660;letter-spacing:-.04em;line-height:1.1}p{margin:8px 0 0;color:var(--text-muted);font-size:13px}section{padding-top:24px;border-top:1px solid var(--border-subtle)}:global(.form-grid){display:grid;gap:18px}:global(.field-row){display:grid;grid-template-columns:1fr 1fr;gap:12px}:global(.field-row .field){grid-template-rows:auto 1fr}:global(.field-row .field>.select),:global(.field-row .field>input){height:100%;min-height:38px}:global(.field){display:grid;gap:7px}:global(.field>span){color:var(--text-strong);font-size:12px;font-weight:620}:global(.field small){color:var(--text-faint);font-size:10px;line-height:1.45}:global(.field input),:global(.field textarea){width:100%;border:1px solid var(--border-strong);border-radius:6px;outline:none;background:var(--surface);color:var(--text-strong);font-size:13px}:global(.field input){height:38px;padding:0 10px}:global(.field textarea){min-height:88px;resize:vertical;padding:10px}:global(.field input:focus),:global(.field textarea:focus){border-color:var(--brand);box-shadow:0 0 0 3px var(--brand-soft)}:global(.form-actions){display:flex;justify-content:flex-end;gap:7px;padding-top:18px;border-top:1px solid var(--border-subtle)}:global(.form-actions a){display:inline-flex;height:36px;align-items:center;padding:0 12px;border:1px solid var(--border);border-radius:6px;background:var(--surface);color:var(--text);cursor:pointer;font-size:12px;font-weight:630;text-decoration:none;transition:background .12s ease,border-color .12s ease,color .12s ease}:global(.form-actions a:hover){border-color:var(--border-strong);background:var(--surface-hover);color:var(--text-strong)}:global(.form-actions a:active){filter:brightness(.94)}@media(max-width:600px){.page{width:calc(100% - 28px);padding-top:32px}:global(.field-row){grid-template-columns:1fr}}
</style>
