<script lang="ts">
  import { renderMarkdown, type MarkdownContext, type MarkdownFormat } from '$lib/markdown';
  let { source, muted = false, variant = 'compact', context, format = 'markdown' } = $props<{ source: string; muted?: boolean; variant?: 'compact' | 'document'; context?: MarkdownContext; format?: MarkdownFormat }>();
  const rendered = $derived(renderMarkdown(source, context, format));
</script>

<div class="markdown" class:muted class:document={variant === 'document'}>{@html rendered}</div>

<style>
  .markdown{color:var(--text);font-size:12px;line-height:1.65;overflow-wrap:anywhere}.markdown.muted{color:var(--text-muted)}
  .markdown :global(:first-child){margin-top:0}.markdown :global(:last-child){margin-bottom:0}.markdown :global(p),.markdown :global(ul),.markdown :global(ol),.markdown :global(blockquote),.markdown :global(pre),.markdown :global(table),.markdown :global(details){margin:0 0 12px}.markdown :global(ul),.markdown :global(ol){padding-left:22px}.markdown :global(li+li){margin-top:3px}.markdown :global(a){color:var(--brand);text-decoration:none}.markdown :global(a:hover){text-decoration:underline}.markdown :global(img){display:block;max-width:100%;height:auto;margin:14px 0}.markdown :global(code){padding:2px 4px;border-radius:4px;background:var(--surface-muted);color:var(--text-strong);font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:.9em}.markdown :global(pre){overflow:auto;padding:11px 13px;border-radius:6px;background:var(--surface-muted)}.markdown :global(pre code){padding:0;background:transparent}.markdown :global(blockquote){padding-left:12px;border-left:2px solid var(--border-strong);color:var(--text-muted)}.markdown :global(h1),.markdown :global(h2),.markdown :global(h3),.markdown :global(h4),.markdown :global(h5),.markdown :global(h6){margin:18px 0 9px;color:var(--text-strong);line-height:1.25}.markdown :global(h1){font-size:18px}.markdown :global(h2){font-size:15px}.markdown :global(h3){font-size:13px}.markdown :global(h4),.markdown :global(h5),.markdown :global(h6){font-size:12px}.markdown :global(hr){height:1px;margin:16px 0;border:0;background:var(--border)}.markdown :global(table){display:block;width:max-content;max-width:100%;overflow:auto;border-spacing:0;border-collapse:collapse}.markdown :global(th),.markdown :global(td){padding:7px 10px;border:1px solid var(--border);text-align:left}.markdown :global(th){background:var(--surface-muted);color:var(--text-strong);font-weight:650}.markdown :global(tr:nth-child(2n) td){background:color-mix(in srgb,var(--surface-muted) 48%,transparent)}.markdown :global(.task-list-item){list-style:none}.markdown :global(.contains-task-list){padding-left:4px}.markdown :global(input[type='checkbox']){display:inline-grid;width:14px;height:14px;margin:0 6px 0 0;border:1px solid var(--border-strong);border-radius:3px;appearance:none;background:var(--surface);vertical-align:-2px;place-items:center}.markdown :global(input[type='checkbox']:checked){border-color:var(--brand);background:var(--brand)}.markdown :global(input[type='checkbox']:checked)::after{width:7px;height:4px;border:solid white;border-width:0 0 2px 2px;content:'';transform:translateY(-1px) rotate(-45deg)}.markdown :global(details){padding:8px 10px;border-radius:6px;background:var(--surface-muted)}.markdown :global(summary){color:var(--text-strong);cursor:pointer;font-weight:630}
  .markdown.document{font-size:13px;line-height:1.7}.markdown.document :global(h1){font-size:27px;letter-spacing:-.035em}.markdown.document :global(h2){padding-bottom:7px;border-bottom:1px solid var(--border);font-size:19px;letter-spacing:-.02em}.markdown.document :global(h3){font-size:16px}.markdown.document :global(h4){font-size:14px}.markdown.document :global(p),.markdown.document :global(ul),.markdown.document :global(ol),.markdown.document :global(blockquote),.markdown.document :global(pre),.markdown.document :global(table),.markdown.document :global(details){margin-bottom:16px}
  .markdown :global(pre.plain-text){overflow:visible;padding:0;border-radius:0;background:transparent;color:inherit;font:inherit;line-height:inherit;white-space:pre-wrap}
</style>
