import type { LanguageInput } from 'shiki/core';

export const languages: Record<string, () => Promise<{ default: LanguageInput[] }>> = {
  'javascript': () => import('@shikijs/langs/javascript'),
  'typescript': () => import('@shikijs/langs/typescript'),
  'jsx': () => import('@shikijs/langs/jsx'),
  'tsx': () => import('@shikijs/langs/tsx'),
  'svelte': () => import('@shikijs/langs/svelte'),
  'html': () => import('@shikijs/langs/html'),
  'css': () => import('@shikijs/langs/css'),
  'scss': () => import('@shikijs/langs/scss'),
  'json': () => import('@shikijs/langs/json'),
  'jsonc': () => import('@shikijs/langs/jsonc'),
  'markdown': () => import('@shikijs/langs/markdown'),
  'rust': () => import('@shikijs/langs/rust'),
  'python': () => import('@shikijs/langs/python'),
  'go': () => import('@shikijs/langs/go'),
  'c': () => import('@shikijs/langs/c'),
  'cpp': () => import('@shikijs/langs/cpp'),
  'csharp': () => import('@shikijs/langs/csharp'),
  'java': () => import('@shikijs/langs/java'),
  'kotlin': () => import('@shikijs/langs/kotlin'),
  'swift': () => import('@shikijs/langs/swift'),
  'ruby': () => import('@shikijs/langs/ruby'),
  'php': () => import('@shikijs/langs/php'),
  'shellscript': () => import('@shikijs/langs/shellscript'),
  'powershell': () => import('@shikijs/langs/powershell'),
  'yaml': () => import('@shikijs/langs/yaml'),
  'toml': () => import('@shikijs/langs/toml'),
  'ini': () => import('@shikijs/langs/ini'),
  'dockerfile': () => import('@shikijs/langs/dockerfile'),
  'makefile': () => import('@shikijs/langs/makefile'),
  'cmake': () => import('@shikijs/langs/cmake'),
  'sql': () => import('@shikijs/langs/sql'),
  'graphql': () => import('@shikijs/langs/graphql'),
  'diff': () => import('@shikijs/langs/diff'),
  'xml': () => import('@shikijs/langs/xml'),
  'vue': () => import('@shikijs/langs/vue'),
  'astro': () => import('@shikijs/langs/astro'),
  'lua': () => import('@shikijs/langs/lua'),
  'zig': () => import('@shikijs/langs/zig'),
  'nix': () => import('@shikijs/langs/nix'),
  'hcl': () => import('@shikijs/langs/hcl'),
};
