/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 930d8cc1311e2222b7ff3276fa30fc94)
interface __BaseEnv_CloudflareBindings {
	OBJECTS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	PUBLIC_URL: string;
	GIT_PUBLIC_URL: string;
	EMAIL_FROM: string;
	AUTH_SECRET: string;
	SECRET_ENCRYPTION_KEY: string;
	GIT_GATEWAY_TOKEN: string;
	PULL_ROOMS: DurableObjectNamespace<import("./src/index").PullRoom>;
	RUN_ROOMS: DurableObjectNamespace<import("./src/index").RunRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PullRoom" | "RunRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLIC_URL" | "GIT_PUBLIC_URL" | "EMAIL_FROM" | "AUTH_SECRET" | "SECRET_ENCRYPTION_KEY" | "GIT_GATEWAY_TOKEN">> {}
}
